version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.5
  node: circleci/node@1.1.6

jobs:
  coveralls:
    executor:
      name: node/default

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: yarn install

      - coveralls/upload:
          parallel: true
          flag_name: Test 1
          verbose: true

workflows:
  coverage:
    jobs:
      - coveralls
        
  
 
